{{- if .Values.ingress.enabled }}
{{- $rules := .Values.ingress.rules | default list }}
{{- if gt (len $rules) 0 }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- $tls := .Values.ingress.tls | default list }}
  {{- if gt (len $tls) 0 }}
  tls:
    {{- toYaml $tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range $rules }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .service }}
                port:
                  number: {{ .port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
