{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
{{- $dns := include "exponat.k8sServiceName" $name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $dns }}
spec:
  selector:
    app: {{ $dns }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ $svc.port }}
  type: ClusterIP
{{- end }}
{{- end }}
