apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base/deployments/api-gateway.yaml
  - ../../base/services/api-gateway.yaml
  - ../../base/configmaps/api-gateway-config.yaml

patches:
  - target:
      kind: Deployment
      name: api-gateway
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
